bztdia/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from users.views import ChatView, CreateChatView, SignInView, SignUpView

urlpatterns = [
    path('signup/', SignUpView.as_view(), name='signup'),
    path('signin/', SignInView.as_view(), name='signin'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('create_chat/', CreateChatView.as_view(), name='create_chat'),
    path('', ChatView.as_view(), name='chat'),
]

users/models.py
from django.contrib.auth.models import User
from django.db import models


class Chat(models.Model):
    users = models.ManyToManyField(User)
    hidden = models.BooleanField(default=True)
    name = models.CharField(max_length=255, blank=False, null=True)

    def __str__(self):
        return f'Чат - {self.name}'


class Message(models.Model):
    chat = models.ForeignKey(Chat, on_delete=models.CASCADE)
    sender = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')


class SignInForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')


class MessageForm(forms.Form):
    content = forms.CharField(widget=forms.Textarea)
    chat_id = forms.IntegerField(widget=forms.HiddenInput())

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.views import View

from .forms import MessageForm, SignInForm, SignUpForm
from .models import Chat, Message


class SignUpView(View):
    template_name = 'users/signup.html'

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('chat')
        form = SignUpForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()

            common_chat, created = Chat.objects.get_or_create()

            common_chat.users.add(user)

            login(request, user)
            return redirect('signin')
        return render(request, self.template_name, {'form': form})


class SignInView(View):
    template_name = 'users/signin.html'

    def get(self, request):
        if request.user.is_authenticated:
            return redirect('chat')
        form = SignInForm()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = SignInForm(request, request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('/')
            else:
                messages.error(request, 'Invalid username or password.')
        else:
            messages.error(request, 'Invalid form submission. Please check your input.')

        return render(request, self.template_name, {'form': form})


class CreateChatView(UserPassesTestMixin, View):
    template_name = 'users/create_chat.html'

    def test_func(self):
        return self.request.user.is_authenticated

    def handle_no_permission(self):
        return redirect('signin')

    def get(self, request):
        users = User.objects.exclude(id=request.user.id)
        return render(request, self.template_name, {'users': users})

    def post(self, request):
        selected_users_ids = request.POST.getlist('selected_users')
        users = User.objects.filter(id__in=selected_users_ids)

        if not users:
            users = User.objects.exclude(id=request.user.id)
            return render(request, self.template_name,
                          {'users': users, 'error_message': 'Select at least one user to create a chat'})

        chat = Chat.objects.create()
        chat_name = request.POST.get('chat_name')

        if not chat_name:
            return render(request, self.template_name, {'users': users, 'error_message': 'Chat name is required'})

        if request.user == chat.users.first() or request.user.is_staff:
            chat.name = request.POST.get('chat_name')
            chat.save()
            chat.users.add(request.user, *users)
            return redirect('/')
        else:
            return redirect('signin')


class ChatView(UserPassesTestMixin, View):
    template_name = 'users/chat.html'

    def test_func(self):
        return self.request.user.is_authenticated

    def handle_no_permission(self):
        return redirect('signin')

    def get(self, request):
        common_chat, created = Chat.objects.get_or_create()

        user_chats = Chat.objects.filter(users=request.user)

        all_chats = user_chats | Chat.objects.filter(id=common_chat.id)

        message_form = MessageForm()
        return render(request, self.template_name, {'chats': all_chats, 'message_form': message_form})

    def post(self, request):
        message_form = MessageForm(request.POST)
        if message_form.is_valid():
            content = message_form.cleaned_data['content']
            chat_id = message_form.cleaned_data['chat_id']
            chat = Chat.objects.get(id=chat_id)
            Message.objects.create(chat=chat, sender=request.user, content=content)
        else:
            print(message_form.errors)

        return redirect('chat')

    def toggle_chat_visibility(self, chat_id):
        chat = Chat.objects.get(id=chat_id)
        chat.hidden = not chat.hidden
        chat.save()

    def get(self, request):
        user_chats = Chat.objects.filter(users=request.user)
        message_form = MessageForm()
        return render(request, self.template_name, {'chats': user_chats, 'message_form': message_form})

    def post(self, request):
        if 'toggle_chat' in request.POST:
            chat_id = request.POST.get('chat_id')
            self.toggle_chat_visibility(chat_id)
            return redirect('chat')

        message_form = MessageForm(request.POST)
        if message_form.is_valid():
            content = message_form.cleaned_data['content']
            chat_id = message_form.cleaned_data['chat_id']
            chat = Chat.objects.get(id=chat_id)
            Message.objects.create(chat=chat, sender=request.user, content=content)
        else:
            print(message_form.errors)

        return redirect('chat')

users/templates/users/chat.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'vendor/css/chat.css' %}">
    <title>Your Chats</title>
</head>
<body>

<nav class="navbar navbar-light navbar-expand-lg" style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'chat' %}">BZTDiA</a>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'create_chat' %}">Create new chat</a>
                </li>
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown"
                       aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<br>

<div class="chat-container">
    <div class="chat-header">
        <h2>Your Chats</h2>
    </div>

    {% for chat in chats %}
    <div class="chat">
        <div class="chat-id">Chat: {{ chat.name }}</div>

        <form method="post" action="{% url 'chat' %}">
            {% csrf_token %}
            <input type="hidden" name="chat_id" value="{{ chat.id }}">
            <button type="submit" class="toggle-button" name="toggle_chat" value="{{ chat.id }}">Toggle Visibility
            </button>
        </form>

        {% if not chat.hidden %}
        <form method="post" action="{% url 'chat' %}" class="message-form">
            <!-- New dropdown list for users in the chat -->
            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="userDropdown{{ chat.id }}"
                        data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Users
                </button>
                <div class="dropdown-menu" aria-labelledby="userDropdown{{ chat.id }}">
                    {% for user in chat.users.all %}
                    <span class="dropdown-item {% if user.is_staff %}admin-user{% endif %} {% if user == request.user %}current-user{% endif %}"
                          style="pointer-events: none;">{{ user.username }}</span>
                    {% endfor %}
                </div>
            </div>
            <br>


            {% csrf_token %}
            <input type="text" name="content" class="message-input" placeholder="Type your message">
            <input type="hidden" name="chat_id" value="{{ chat.id }}">
            <button type="submit" class="send-button">Send Message</button>
        </form>

        <ul class="message-list">
            {% for message in chat.message_set.all %}
            {% if message.sender == user %}
            <li class="user-message" style="text-align: right;">{{ message.content }}</li>
            {% elif message.sender.is_staff %}
            <li class="admin-message" style="text-align: left;"><span
                    style="color: red;">{{ message.sender.username }}</span>: {{ message.content }}
            </li>
            {% else %}
            <li class="other-message" style="text-align: left;">{{ message.sender.username }}: {{ message.content }}
            </li>
            {% endif %}
            {% endfor %}
        </ul>
        {% endif %}

        <hr>
    </div>
    {% endfor %}
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>

<script>
    // Prevent clicking on individual users in the dropdown
    document.querySelectorAll('.dropdown-item').forEach(function(item) {
        item.addEventListener('click', function(e) {
            e.stopPropagation();
        });
    });











</script>
</body>
</html>

users/templates/users/create_chat.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'vendor/css/create_chat.css' %}">
    <title>Create a Chat</title>
</head>
<body>

<nav class="navbar navbar-light navbar-expand-lg" style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'chat' %}">BZTDiA</a>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'chat' %}">Back to chats</a>
                </li>
            </ul>

            <ul class="navbar-nav">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-bs-toggle="dropdown"
                       aria-expanded="false">
                        {{ user.username }}
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>
<br>

<div class="create-chat-container">
    <h2>Create a Chat</h2>

    <!-- Add this snippet to display error messages -->
    {% if error_message %}
    <div class="alert alert-danger" role="alert">
        {{ error_message }}
    </div>
    {% endif %}

    <form method="post" action="{% url 'create_chat' %}">
        {% csrf_token %}
        <label for="chat_name">Chat Name:</label>
        <input type="text" name="chat_name" id="chat_name" class="form-control"><br>

        {% for user in users %}
        <div class="form-check">
            <input type="checkbox" class="form-check-input" name="selected_users" value="{{ user.id }}"
                   id="user{{ user.id }}">
            <label class="form-check-label" for="user{{ user.id }}">{{ user.username }}</label>
        </div>
        {% endfor %}

        <button type="submit" class="btn btn-primary">Create Chat</button>
    </form>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
        crossorigin="anonymous"></script>
</body>
</html>

users/templates/users/signin.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Material Compact Login Animation</title>

    <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>
    <link rel='stylesheet prefetch'
          href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900&subset=latin,latin-ext'>
    <link rel="stylesheet" href="{% static 'vendor/css/style.css' %}">

   <style>
        /* Add this to your existing CSS or create a new style tag */
        .admin {
            background-color: yellow; /* You can change the style as needed */
            font-weight: bold;
        }

        /* Add styles for error messages */
        .error-messages {
            background-color: #ff4d4d; /* Red background color */
            color: #fff; /* White text color */
            padding: 10px; /* Padding for better appearance */
            margin-bottom: 10px; /* Margin to separate from other elements */
        }

        .error-messages ul {
            list-style: none;
            margin: 0;
            padding: 0;
        }

        .error-messages li {
            margin-bottom: 5px;
        }
    </style>
</head>

<body>
{% if messages %}
        <div class="error-messages">
            <ul>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}

<div class="materialContainer">
    <form method="post" action="{% url 'signin' %}">
        {% csrf_token %}
        <div class="box">
            <div class="title">LOGIN</div>

            <div class="input">
                <label for="{{ form.username.id_for_label }}">Username</label>
                {{ form.username }}
                <span class="spin"></span>
            </div>

            <div class="input">
                <label for="{{ form.password.id_for_label }}">Password</label>
                {{ form.password }}
                <span class="spin"></span>
            </div>

            <div class="button login">
                <button><span>GO</span> <i class="fa fa-check"></i></button>
            </div>
        </div>
    </form>

    <a href="{% url 'signup' %}">
        <div class="alt-2"><span class="shape"></span></div>
    </a>

    <!-- Example of displaying the user with conditional class -->
    <div class="user-info {% if user.is_staff %}admin{% endif %}">
        {{ user.username }}
        <!-- Other user information as needed -->
    </div>
</div>

<script src="//code.jquery.com/jquery-1.7.1.min.js"></script>
<script src="{% static 'vendor/js/index.js' %}"></script>
</body>
</html>

users/templates/users/signup.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Material Compact Login Animation</title>

    <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>
    <link rel='stylesheet prefetch'
          href='http://fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900&subset=latin,latin-ext'>
    <link rel="stylesheet" href="{% static 'vendor/css/style.css' %}">
    <!--    <style>-->
    <!--        .error-message {-->
    <!--            color: #ff0000;-->
    <!--            font-size: 14px;-->
    <!--            margin-top: 5px;-->
    <!--        }-->
    <!--    </style>-->
    <style>
        /* Add styles for error messages */
        .error-messages {
            background-color: #ff4d4d; /* Red background color */
            color: #fff; /* White text color */
            padding: 10px; /* Padding for better appearance */
            margin-bottom: 10px; /* Margin to separate from other elements */
        }

        .error-messages ul {
            list-style: none;
            margin: 0;
            padding: 0;
        }

        .error-messages li {
            margin-bottom: 5px;
        }

    </style>
</head>

<body>
{% if form.errors %}
<div class="error-messages">
    <ul>
        {% for message in form.non_field_errors %}
        <li>{{ message }}</li>
        {% endfor %}
        {% for field, errors in form.errors.items %}
        {% for error in errors %}
        <li>{{ field|capfirst }}: {{ error }}</li>
        {% endfor %}
        {% endfor %}
    </ul>
</div>
{% endif %}
<div class="materialContainer">
    <form method="post" action="{% url 'signup' %}">
        {% csrf_token %}
        <div class="box">
            <div class="title">Register</div>

            <div class="input">
                <label for="{{ form.username.id_for_label }}">Username</label>
                {{ form.username }}
                <span class="spin"></span>
                <!-- Display field-specific errors -->
                <div class="error-message">{{ form.username.errors }}</div>
            </div>

            <div class="input">
                <label for="{{ form.password1.id_for_label }}">Password</label>
                {{ form.password1 }}
                <span class="spin"></span>
                <!-- Display field-specific errors -->
                <!--                <div class="error-message">{{ form.password1.errors }}</div>-->
            </div>

            <div class="input">
                <label for="{{ form.password2.id_for_label }}">Repeat password</label>
                {{ form.password2 }}
                <span class="spin"></span>
                <!-- Display field-specific errors -->
                <!--                <div class="error-message">{{ form.password2.errors }}</div>-->
            </div>
            <br>

            <div class="button login">
                <button><span>GO</span> <i class="fa fa-check"></i></button>
            </div>
            <a href="{% url 'signin' %}" class="pass-forgot">Login</a>
        </div>
    </form>
</div>
<script src="//code.jquery.com/jquery-1.7.1.min.js"></script>
<script src="{% static 'vendor/js/index.js' %}"></script>
</body>
</html>